tablebookingDb:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: 1
    POSTGRES_USER: postgres
    POSTGRES_DB: tablebooking

rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"