# Database
logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace
spring:
    datasource:
        url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: ${DATABASE_DDL}
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    jackson:
        serialization:
            write_dates_as_timestamps: false
    mail:
        host: ${MAIL_HOST}
        password: 43:-_/deYwNC
        port: 587
        properties:
            mail:
                smtp:
                    auth: true;
                    starttls:
                        enable: true
                        required: true
        username: ${MAIL_USERNAME}
    rabbitmq:
        host: rabbitmq

# Swagger
springfox:
    documentation:
        swagger:
            v2:
                path: /documentation/swagger