spring:
    application:
        name: mamstolik
        version: 0.41.0
        logServer: 54.37.138.131:5000
        type: ${TYPE}
    datasource:
        url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: ${DATABASE_DDL}
        properties:
            hibernate:
                format_sql: false
                connection:
                    char_set: UTF-8
                hbm2ddl:
                    import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        show-sql: false
    jackson:
        serialization:
            write_dates_as_timestamps: false
    mail:
        host: ${MAIL_HOST}
        password: 43:-_/deYwNC
        port: 587
        properties:
            mail:
                smtp:
                    auth: true;
                    starttls:
                        enable: true
                        required: true
        username: ${MAIL_USERNAME}
    rabbitmq:
        host: rabbitmq
        port: ${RABBITMQ_PORT}
    http:
        multipart:
            max-file-size: 3Mb
            max-request-size: 3Mb

# Swagger
springfox:
    documentation:
        swagger:
            v2:
                path: /documentation/swagger

front-web:
    protocol: ${WEB_PROTOCOL}
    hostname: ${WEB_HOSTNAME}
    port: ${WEB_PORT}

logbook:
    exclude:
        - /health
        - /admin/**
    filter.enabled: true
    format.style: json
    obfuscate:
        headers:
            - Authorization
            - X-Secret
        parameters:
            - access_token
            - password
            - newPassword
    write:
        category: http.wire-log
        level: INFO
        chunk-size: 8000

flyway:
    enabled: ${FLYWAY_ENABLED}
    locations: classpath:/db/migration
    baseline-on-migrate: ${FLYWAY_BASELINE}